SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, 
        CASE FREEZER_YN
        WHEN 'Y' THEN 'Y'
        ELSE 'N'
        END
        AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID
